language: python
python:
  - "3.7"
services:
  - docker
before_script:
  - pip install docker-compose
script:
  - docker-compose build
  - docker-compose run app sh -c  "sleep 7; python manage.py test && flake8"